function select_selective(x){
	switch(x){
		case 1:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Azul - Papel e Papelão";
			document.getElementById("modal_info").innerHTML = "O processo de reciclagem do papel começa pela seleção do material, com a separação do material que será utilizado para ser colocado em contentores que irão gerar fibras novas para produção de papel a partir das fibras velhas. Normalmente as fibras recicladas são misturadas a pastas de refinador com fibras virgens. Essa nova mistura de pasta de celulose é submetida a um processo de refinamento e depuração onde o novo papel irá ganhar mais resistência e qualidade. Neste processo são retirados excessos de materiais contaminantes para o papel reciclado. Ao final a pasta é levada para a secagem e formatação. Após esse processo a reciclagem do papel se conclui e o novo material poderá novamente ser introduzido ao mercado consumidor.";
			document.getElementById("modal_categ").innerHTML = "<h5>Categorias</h5>1) papel imprensa, destinado majoritariamente à impressão de jornais, mas também inclui periódicos, revistas, listas telefônicas, suplementos e encartes promocionais;<br>2) de imprimir e escrever;<br>3) papelão ondulado, majoritariamente dirigido para a produção de embalagens para transporte das mais variadas mercadorias;<br>4) papel-cartão, especialmente utilizado na produção de embalagens de bens de consumo imediato, como remédios, alimentos industrializados, cosméticos e brinquedos, entre outros;<br>5) sanitários, cujo principal produto é o papel higiênico, mas também engloba a produção de toalhas, guardanapos e lenços, entre outros produtos;<br>6) outros papéis para embalagens e os papéis especiais.<br><br>";
			document.getElementById("modal_dica").innerHTML = "Pergunte para alguém que mexa com artesanato se não vai querer o papelão que você tem na sua casa, as vezes pode ajudar essa pessoa e assim ajudando o meio ambiente.";
			document.getElementById("modal_link").innerHTML = "https://www.infoescola.com/ecologia/reciclagem-de-papel/";
		break;

		case 2:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Vermelha - Plástico";
			document.getElementById("modal_info").innerHTML = "Alguns materiais poliméricos possuem uma característica térmica que permite que os mesmos sejam reciclados através do emprego de temperatura, onde estes materiais passam do estado sólido para o estado líquido pastoso (fundido), e podem ser reprocessados através dos diversos tipos de processos de transformação existentes.<br> Os materiais poliméricos que possuem essa característica de reprocessabilidade são os termoplásticos. Parece um processo simples, mas requer muita atenção, pois os resíduos que são reciclados passam por algumas etapas antes de poderem passar pela etapa de reprocessamento, além disso é necessário separar os materiais termoplásticos de acordo com o polímero do qual o resíduo é feito, para que no momento de reprocessá-los não haja degradação devido à incompatibilidade de materiais.";
			document.getElementById("modal_categ").innerHTML = "<h5>Classificação</h5>1) PET<br>2) PEAD<br>3) PVC<br>4) PEBD<br>5) PP<br>6) PS<br>7) Outros<br><br>";
			document.getElementById("modal_dica").innerHTML = "Sempre lave as embalagens antes de coloca na seletiva, a água pode ser a de reuso, assim já ajuda na economia da água. A importância do material ser lavado é que ajuda muito no momento da triagem e o aproveitamento do material.";
			document.getElementById("modal_link").innerHTML = "https://www.infoescola.com/ecologia/reciclagem-de-plasticos/";
		break;

		case 3:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Verde - Vidro";
			document.getElementById("modal_info").innerHTML = "O vidro é infinitamente reciclável, pode ser reciclado muitas vezes sem perder suas qualidades. Um material de vidro reciclado possui as mesmas qualidades que um fabricado com matérias-primas virgens. O vidro também é 100% reciclável, ou seja, não há perda de material durante o processo. Para cada tonelada de caco de vidro, uma tonelada de vidro novo é produzida. Por outro lado, para que a mesma quantidade de vidro seja produzida seriam necessárias 1,2 toneladas de matéria-prima.A coleta seletiva é o primeiro passo para que o processo de reciclagem seja realizado. A maneira mais simples de separação dos resíduos é separar os materiais recicláveis dos não recicláveis.<br> A coleta do material reciclável pode ser feita porta a porta pelo sistema de coleta seletiva da região, ou o material pode ser entregue diretamente às unidades de recebimento. O vidro coletado é encaminhado para as empresas responsáveis pela triagem, limpeza e comercialização de vidros. Nesses locais o vidro passa por um processo de separação, por tipo e cor, e por um rigoroso processo de limpeza, através do qual todas as impurezas, como tampas, gargalos de metal, papéis, restos de produtos químicos, etc. são removidas. Estes materiais causam danos ao processo de reciclagem e interferem na qualidade final do novo produto.";
			document.getElementById("modal_categ").innerHTML = "";
			document.getElementById("modal_dica").innerHTML = "Lave com água de reuso e tire a tampa, assim ajuda muito.";
			document.getElementById("modal_link").innerHTML = "https://www.infoescola.com/ecologia/reciclagem-de-vidro/";
		break;

		case 4:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Amarela - Metal";
			document.getElementById("modal_info").innerHTML = "Os metais possuem elevada durabilidade e resistência mecânica e são utilizados para a fabricação de inúmeros itens, como latas, móveis, peças automotivas, utensílios de cozinha, fios elétricos, etc. Os metais são classificados em dois grandes grupos, de acordo com a sua composição: ferrosos (basicamente ferro e aço) e não ferrosos (alumínio, cobre, chumbo, níquel, zinco). A reciclagem dos metais é uma atividade bastante eficiente, pois o metal pode ser reciclado inúmeras vezes, além disso, o metal reciclado tem praticamente todas as propriedades do metal comum.<br> O processo de reciclagem do metal depende primeiramente das fases de coleta e separação dos materiais. Os resíduos metálicos coletados são separados nos centros de triagem entre ferrosos e não ferrosos e também por tipo e características (alumínio, cobre, ferro, aço, etc.). Como os metais ferrosos possuem propriedades magnéticas, sua separação dos demais resíduos pode ser feita por meio do uso de eletroímãs. Os resíduos já separados são prensados, classificados e encaminhados para as estações de reciclagem específicas. Nessas estações os resíduos são livrados das impurezas, triturados, derretidos e transformados em novos produtos.";
			document.getElementById("modal_categ").innerHTML = "<h5>Metais não reciclaveis</h5>Clipes<br>Grampos<br>Esponjas de aço<br>Latas de tinta e de combustível.<br><br>";
			document.getElementById("modal_dica").innerHTML = "Latas amassadas e bem armazenadas.";
			document.getElementById("modal_link").innerHTML = "https://www.infoescola.com/ecologia/reciclagem-de-metais/";
		break;

		case 5:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Preta - Madeira";
			document.getElementById("modal_info").innerHTML = "A madeira em si deve ser repassada para empresas parceiras que possuem processos produtivos e clientela específica no sentido de gerar lucro ao processo sustentável.<br> Reciclagem de madeira é deita por prestadores de serviço e indústrias, parcerias existentes para gerar emprego e ao mesmo tempo aproveitar os recursos naturais que em geral são dispensados com pouco critério ao reuso.<br>Quando o aproveitamento se torna impossível para fábricos de produtos o resíduo deve ser encaminhado às indústrias com maior porte e capazes de utilizar o item na construção civil ou dentro do mercado de novelas e cinemas, conhecidos por aproveitarem a madeira à construção de cenários. Interessante notar que a madeira pode participar de diversas formas para reciclar. Tecnologia permite que diferentes fontes madeireiras sejam aproveitadas, tais como: Galhos, troncos de árvores, caixões, caixas, móveis e ripas da construção civil.<br> Após acontecer a transformação em pequenos fragmentos a madeira também pode ser útil para fabricar artesanatos. Dentro da casa a criatividade pode representar excelente aliada ao reaproveitamento. Também pode ser encaminhada como forma de combustível de forno a lenta, seja nas churrasqueiras ou para aquecer pizzas.<br> Necessário levar em conta de que pode ser útil para substituir combustíveis fósseis considerados escassos na sociedade, como petróleo e carvão, dentro das usinas e indústria. Método que ajude de modo principal o bem-estar ecológico do meio ambiente.<br> Reaproveitar tem importância ao meio ambiente e florestas tropicais estabelecidas das florestas ao redor do mundo. Nos dias atuais existe a estimativa de que a Mata Atlântica possui apenas 7% da vegetação nativa encontrada na época do descobrimento do Brasil. Outra importância significativa está em diminuir o índice de lixo existente dentro dos aterros sanitários e lixões.";
			document.getElementById("modal_categ").innerHTML = "<h5>Desvantagem da reciclagem de madeira</h5>Existem alguns obstáculos para a adoção generalizada de madeira reciclada. Às vezes, as extremidades da parede com parafusos precisam ser aparadas para interromper movimentos de decadência e rachaduras, o que resulta em um longo pedaço de madeira que não atendem os códigos. <br>Embora o preço possa ser menor do que para a madeira nova, o processo de seleção de peças utilizáveis pode ser trabalhoso e demorado. <br><br>";
			document.getElementById("modal_dica").innerHTML = "Pergunte para um artesão se não é de interesse a madeira, ou até mesmo para um marceneiro.";
			document.getElementById("modal_link").innerHTML = "https://meioambiente.culturamix.com/recursos-naturais/como-e-feita-a-reciclagem-da-madeira";
		break;

		case 6:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Laranja - Perigoso ou contaminados";
			document.getElementById("modal_info").innerHTML = "Os resíduos perigosos, mesmo que não saibamos de sua classificação, estão bastante presentes em nosso dia a dia. Baterias, pilhas, remédios vencidos, cartuchos de tinta, latas de tinta, tonners, pneus, lâmpadas fluorescentes, dentre muitos outros materiais que fazemos uso quase que diário são considerados como resíduos perigosos.<br>Infelizmente, devido ao baixo grau de instrução e de conscientização de nossa população, os resíduos perigosos gerados todos os dias em nossos domicílios são descartados de maneira incorreta, colocando em risco a vida de muitos seres vivos, incluindo os seres humanos.<br>Isso porque na composição dos resíduos perigosos estão presentes diversos componentes altamente tóxicos, ricos em substâncias químicas e metais pesados, capazes de contaminar o solo, cursos d’água, lençol freático e, consequentemente, o meio ambiente como um todo.<br>Assim, além de uma maior oferta de pontos de recebimento desses materiais, é necessária uma maior participação do poder público tanto na promoção da conscientização da população, quanto na punição a ser aplicada tanto aos cidadãos quanto aos fabricantes, importadores ou revendedores que desobedecerem as normas especificadas.";
			document.getElementById("modal_categ").innerHTML = "";
			document.getElementById("modal_dica").innerHTML = "Mantenha distância e cuidado na hora de por na lata seletiva, tenha cuidado para entra em contato com a pele.";
			document.getElementById("modal_link").innerHTML = "https://www.dinamicambiental.com.br/blog/reciclagem/a-correta-destinacao-de-residuos-perigosos/";
		break;

		case 7:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Branca - Ambulatórios ou de serviços de saúde.";
			document.getElementById("modal_info").innerHTML = "O lixo hospitalar, também chamado de resíduo hospitalar e de resíduo de serviços de saúde, é todo tipo de lixo proveniente do atendimento a pacientes ou de qualquer estabelecimento de saúde ou unidade que execute atividades de natureza de atendimento médico, tanto para seres humanos quanto para animais. Esse tipo de lixo também pode ser encontrado em locais como centros de pesquisa e laboratórios de farmacologia. Seja qual for sua origem ou tipo, o descarte do lixo hospitalar deve ser feito seguindo regras específicas que evitem contaminação ambiental.<br>O lixo hospitalar pode representar risco à saúde humana e ao meio ambiente se não houver adoção de procedimentos técnicos adequados no manejo dos diferentes tipos de lixo gerados. Alguns exemplos de lixo hospitalar são materiais biológicos contaminados com sangue ou patógenos, peças anatômicas, seringas e outros materiais plásticos; além de uma grande variedade de substâncias tóxicas, inflamáveis e até radioativas.";
			document.getElementById("modal_categ").innerHTML = "<h5>Tipos de lixo hospitalar</h5> <strong>Grupo A (potencialmente infectantes)</strong> - que tenham presença de agentes biológicos que apresentem risco de infecção. Ex.: bolsas de sangue contaminado;<br><br><strong>Grupo B (químicos)</strong> - que contenham substâncias químicas capazes de causar risco à saúde ou ao meio ambiente, independente de suas características inflamáveis, de corrosividade, reatividade e toxicidade. Por exemplo, medicamentos para tratamento de câncer, reagentes para laboratório e substâncias para revelação de filmes de Raio-X;<br><br><strong>Grupo C (rejeitos radioativos)</strong> - materiais que contenham radioatividade em carga acima do padrão e que não possam ser reutilizados, como exames de medicina nuclear;<br><br><strong>Grupo D (resíduos comuns)</strong> - qualquer lixo hospitalar que não tenha sido contaminado ou possa provocar acidentes, como gesso, luvas, gazes, materiais passíveis de reciclagem e papéis;<br><br><strong>Grupo E (perfurocortantes)</strong> - objetos e instrumentos que possam furar ou cortar, como lâminas, bisturis, agulhas e ampolas de vidro.<br><br>";
			document.getElementById("modal_dica").innerHTML = "Sempre pegue com luvas e lave bem as mãos depois, nunca se sabe qual bactéria teve em contato com aquilo.";
			document.getElementById("modal_link").innerHTML = "https://www.ecycle.com.br/3237-lixo-hospitalar";
		break;

		case 8:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Roxa - Radioativos.";
			document.getElementById("modal_info").innerHTML = "Por emitir grande carga de radiação, o armazenamento do resíduo radioativo deve ser muito cauteloso. A Agência Internacional de Energia Atômica (AIEA), que faz parte da Organização das Nações Unidas (ONU), exige que o lixo nuclear seja embalado e armazenado de forma isolada até que ele não ofereça mais riscos ao meio ambiente e à saúde humana. Porém, ainda não existe um método que seja 100% eficiente e seguro para lidar com os rejeitos radioativos.<br>O que é feito atualmente é a classificação dos resíduos em três tipos: alta, média e baixa radioatividade. A partir daí, cada tipo é armazenado de uma forma. Os lixos de nível baixo — tais como ferramentas, luvas, roupas de proteção e materiais médicos — e médio — peças de reatores e rejeitos químicos de processos de mineração e enriquecimento de urânio — são guardados em depósitos provisórios ou permanentes, como tambores e tonéis lacrados ou tanques de aço inoxidável, revestidos de concreto. Nesses locais, o lixo nuclear deve ficar isolado por períodos que variam de 50 a 300 anos.<br>Por sua vez, resíduos de alta radioatividade, como restos de combustível nuclear e rejeitos oriundos da extração de plutônio, devem ser colocados em piscinas de resfriamento junto aos próprios reatores das usinas. Em seguida, toda a estrutura é cercada por várias barreiras de aço, chumbo e concreto. Nesse caso, o lixo deve ficar isolado por tempo indeterminado.";
			document.getElementById("modal_categ").innerHTML = "<h5>Problemas ambientais causados pelo lixo radioativo</h5>O lixo radioativo está associado a impactos ambientais, como a contaminação das águas e da atmosfera, causando danos à vegetação e aos animais, o que resulta na degradação gradual da biodiversidade.<br>Pessoas atingidas pela radioatividade podem contrair infecções, convulsões, câncer e vários outros malefícios que podem levar, inclusive, à morte.<br><br>";
			document.getElementById("modal_dica").innerHTML = "Mantenha a distância, não seja curioso, pode causar graves ferimentos ou até mesmo vim a óbito.";
			document.getElementById("modal_link").innerHTML = "https://www.fragmaq.com.br/blog/feito-descarte-lixo-radioativo/";
		break;

		case 9:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Marrom - Orgânicos.";
			document.getElementById("modal_info").innerHTML = "É possível reciclar alimentos, folhas e sementes? A resposta é sim e, inclusive, essa prática de reciclagem de lixo orgânico está sendo cada vez mais utilizada.<br>A produção de energia (biogás) é um exemplo de processo de reciclagem onde esse tipo de lixo pode ser utilizado, uma vez que sua decomposição gera gás metano.<br>Outra possibilidade é a compostagem. Ela transforma o lixo orgânico em adubo o que é favorável tanto ao meio ambiente, uma vez que esse material não será despejado em aterros sanitários, quanto ao solo que será amparado por um material bastante nutritivo. O mais legal é que esse método pode ser feito em casa.";
			document.getElementById("modal_categ").innerHTML = "";
			document.getElementById("modal_dica").innerHTML = "Cascas de frutas, ovo e alguns outros alimentos serve de adubo para plantinhas, fazendo a reutilização da mesma para ajudar a saúde das plantas sendo totalmente sustentável, e ajudando o meio ambiente.";
			document.getElementById("modal_link").innerHTML = "https://www.dinamicambiental.com.br/blog/reciclagem/lixo-organico-reciclado/";
		break;

		case 10:
			document.getElementById("modal_titulo").innerHTML = "Seletiva Cinza - Não reciclaveis ou misturados.";
			document.getElementById("modal_info").innerHTML = "A reciclagem é um ato de extrema importância nos dias atuais. Além de ajudar na preservação do meio ambiente, gera renda para milhares de pessoas.<br>Porém, por questões técnicas, nem todos os materiais descartados por pessoas ou indústrias podem passar pelo processo de reciclagem estes, após passarem por processos industriais, não podem ser reutilizados e tem como destino o lixo comum.";
			document.getElementById("modal_categ").innerHTML = "";
			document.getElementById("modal_dica").innerHTML = "evite objetos assim, pois são prejudiciais ao meio ambiente!";
			document.getElementById("modal_link").innerHTML = "https://www.sobiologia.com.br/conteudos/reciclagem/<br>reciclagem11.php";
		break;
	}
	$('#modal_selective').modal('show');
}